name: Build and Release
on:
  push:
    branches:
      - main

jobs:
  build-release:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build library
        run: ./gradlew --no-daemon build
      - name: Copy private keys
        run: echo ${{ secrets.PRIVKEY }} > privkey.asc
      - name: Create publication
        run: ./gradlew --no-daemon -Psign.passphrase=${{ secrets.PASSPHRASE }} publishMavenPublicationToMavenRepository
      - name: Make JReleaser directory
        run: mkdir build/jreleaser
      - name: Release library
        run: ./gradlew --no-daemon -Psonatype.username=${{ secrets.SONATYPE_USERNAME }} -Psonatype.password=${{ secrets.SONATYPE_PASSWORD }} -Pgithub.token=${{ secrets.GITHUB_TOKEN }} jreleaserRelease